#!/usr/bin/env bash
# Generate a ready-to-paste Portainer stack env file for AI Exam Generator.
# Requires: openssl, and either node or python3.
set -euo pipefail

have() { command -v "$1" >/dev/null 2>&1; }

if ! have openssl; then
  echo "Error: openssl is required" >&2
  exit 1
fi

gen_hex() { openssl rand -hex "$1"; }
gen_base64() { openssl rand -base64 "$1" | tr -d '\n'; }

# HS256 JWT (anon / service_role) from JWT_SECRET
sign_jwt() {
  local role="$1" secret="$2" iat="$3" exp="$4"
  if have node; then
    JWT_SECRET="$secret" JWT_ROLE="$role" JWT_IAT="$iat" JWT_EXP="$exp" node <<'NODE'
const crypto = require('crypto');
const secret = process.env.JWT_SECRET;
const role = process.env.JWT_ROLE;
const iat = Number(process.env.JWT_IAT);
const exp = Number(process.env.JWT_EXP);
const b64url = (buf) => Buffer.from(buf).toString('base64url');
const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
const payload = b64url(JSON.stringify({ role, iss: 'supabase', iat, exp }));
const data = `${header}.${payload}`;
const sig = crypto.createHmac('sha256', secret).update(data).digest('base64url');
process.stdout.write(`${data}.${sig}`);
NODE
  elif have python3; then
    JWT_SECRET="$secret" JWT_ROLE="$role" JWT_IAT="$iat" JWT_EXP="$exp" python3 <<'PY'
import base64, hashlib, hmac, json, os
def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")
secret = os.environ["JWT_SECRET"].encode()
role = os.environ["JWT_ROLE"]
iat = int(os.environ["JWT_IAT"])
exp = int(os.environ["JWT_EXP"])
header = b64url(json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":")).encode())
payload = b64url(json.dumps({"role": role, "iss": "supabase", "iat": iat, "exp": exp}, separators=(",", ":")).encode())
data = f"{header}.{payload}".encode()
sig = b64url(hmac.new(secret, data, hashlib.sha256).digest())
print(f"{data.decode()}.{sig}", end="")
PY
  else
    echo "Error: need node or python3 to sign JWTs" >&2
    exit 1
  fi
}

SITE_URL="${SITE_URL:-https://examgenerator.neonex.site}"
API_EXTERNAL_URL="${API_EXTERNAL_URL:-${SITE_URL}/auth/v1}"

POSTGRES_PASSWORD="$(gen_hex 24)"
JWT_SECRET="$(gen_base64 40)"
DASHBOARD_USERNAME="${DASHBOARD_USERNAME:-aiexam}"
DASHBOARD_PASSWORD="$(gen_hex 16)"
SECRET_KEY_BASE="$(gen_base64 48)"
VAULT_ENC_KEY="$(gen_hex 16)"
PG_META_CRYPTO_KEY="$(gen_base64 24)"
PROVIDER_SECRETS_KEY="$(gen_base64 32)"
GENERATION_WORKER_SECRET="$(gen_hex 24)"
SEED_SECRET="$(gen_hex 16)"
REALTIME_DB_ENC_KEY="$(gen_hex 8)"
S3_PROTOCOL_ACCESS_KEY_ID="$(gen_hex 16)"
S3_PROTOCOL_ACCESS_KEY_SECRET="$(gen_hex 32)"

iat="$(date +%s)"
exp=$((iat + 5 * 365 * 24 * 3600))
ANON_KEY="$(sign_jwt anon "$JWT_SECRET" "$iat" "$exp")"
SERVICE_ROLE_KEY="$(sign_jwt service_role "$JWT_SECRET" "$iat" "$exp")"

cat <<EOF
############
# Generated by deploy/generate-secrets.sh — paste into Portainer stack env.
# Do NOT commit the real values.
############

# --- URLs ---
SITE_URL=${SITE_URL}
API_EXTERNAL_URL=${API_EXTERNAL_URL}
ADDITIONAL_REDIRECT_URLS=
APP_HOST_PORT=3300
STUDIO_HOST_PORT=3301

# --- Core secrets ---
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=postgres
POSTGRES_PORT=5432
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=3600
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DASHBOARD_USERNAME=${DASHBOARD_USERNAME}
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
SECRET_KEY_BASE=${SECRET_KEY_BASE}
VAULT_ENC_KEY=${VAULT_ENC_KEY}
PG_META_CRYPTO_KEY=${PG_META_CRYPTO_KEY}
REALTIME_DB_ENC_KEY=${REALTIME_DB_ENC_KEY}
PROVIDER_SECRETS_KEY=${PROVIDER_SECRETS_KEY}
GENERATION_WORKER_SECRET=${GENERATION_WORKER_SECRET}
SEED_SECRET=${SEED_SECRET}

# Optional opaque API keys (leave empty for legacy HS256 JWTs only)
SUPABASE_PUBLISHABLE_KEY=
SUPABASE_SECRET_KEY=
ANON_KEY_ASYMMETRIC=
SERVICE_ROLE_KEY_ASYMMETRIC=

# --- Auth ---
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=true

# --- SMTP (GoTrue + edge send-email) ---
SMTP_ADMIN_EMAIL=noreply@neonex.site
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_SENDER_NAME="AI Exam Generator"
SMTP_FROM=
SMTP_SECURE=false
MAILER_URLPATHS_INVITE=/auth/v1/verify
MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
MAILER_URLPATHS_RECOVERY=/auth/v1/verify
MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify
RESEND_API_KEY=
EMAIL_FROM=
EMAIL_FROM_NAME="AI Exam Generator"

# --- Studio / PostgREST / Storage ---
STUDIO_DEFAULT_ORGANIZATION=Neonex
STUDIO_DEFAULT_PROJECT="AI Exam Generator"
PGRST_DB_SCHEMAS=public,graphql_public,storage
PGRST_DB_MAX_ROWS=1000
PGRST_DB_EXTRA_SEARCH_PATH=public
FUNCTIONS_VERIFY_JWT=false
STORAGE_TENANT_ID=stub
REGION=stub
GLOBAL_S3_BUCKET=stub
S3_PROTOCOL_ACCESS_KEY_ID=${S3_PROTOCOL_ACCESS_KEY_ID}
S3_PROTOCOL_ACCESS_KEY_SECRET=${S3_PROTOCOL_ACCESS_KEY_SECRET}
IMGPROXY_AUTO_WEBP=true

# --- Seed (prod: leave false) ---
SEED_DEMO_USERS=false

# --- Optional LLM provider keys (or configure in Studio / Settings UI) ---
OPENAI_API_KEY=
OPENAI_QUESTION_MODEL=gpt-4o
GEMINI_API_KEY=
GEMINI_QUESTION_MODEL=gemini-1.5-pro
ANTHROPIC_API_KEY=
ANTHROPIC_QUESTION_MODEL=claude-3-5-sonnet-latest
COMPAT_API_KEY=
COMPAT_BASE_URL=
COMPAT_QUESTION_MODEL=
AI_MAX_OUTPUT_TOKENS=8000
AI_TIMEOUT_MS=120000
EOF
